### ISSUE TITLE
<alt>: rendering

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#20] opened 2015-09-28 16:09 UTC
see https://faustedition.uni-wuerzburg.de/wiki/index.php/Einblendungsapparat#Alternativen_.28tei:alt.29

Also applicable for the rendering of texts in their "latest stage".

**Comment by thvitt** [comment] 2015-09-30 10:47
duplicate of #16

**Closed by thvitt** 2015-09-30 10:47 UTC
Labels: duplicate, Einblendungsapparat
